# phpmyadmin only with persist data
version: '2'
services:
  dataVolumes:
    image: debian
    container_name: dataVolumes
    command: bash /usr/local/bin/forever.sh
    volumes:
      # map directory to save mysql databses
      # Do not forget to change below to suit your directory.
      # It's only keeping data
      # if the mysqlServer container below use this dataVolumes
      - F:\Docker\Data\Databases\Mysql:/var/lib/mysql
      - ./forever.sh:/usr/local/bin/forever.sh

  mysqlServer:
    image: mysql:5.6
    container_name: mysqlServer
    ports:
      # I already have mysql install on my computer so I need to use another port than 3306
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # Uncomment below to persist the data permanently on the server
    #volumes_from:
    #  - dataVolumes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysqlServer:db
    ports:
      - 8081:80
